// <auto-generated />
using System;
using CollegeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeApp.Migrations
{
    [DbContext(typeof(CollegeDBContext))]
    partial class CollegeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeApp.Data.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("index-Department-Id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "KHMT001",
                            DepartmentName = "Khoa học máy tính",
                            Description = "Sinh viên thuộc nghành khoa học máy tính"
                        },
                        new
                        {
                            Id = "Luat001",
                            DepartmentName = "Luật học",
                            Description = "Sinh viên thuộc luật học"
                        },
                        new
                        {
                            Id = "CNTT001",
                            DepartmentName = "Công nghệ thông tin",
                            Description = "Sinh viên thuộc nghành công nghệ thông tin"
                        });
                });

            modelBuilder.Entity("CollegeApp.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Id")
                        .HasDatabaseName("index-Student-Id");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Tĩnh",
                            DOB = new DateTime(2003, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "KHMT001",
                            Email = "hoangquy3125@gmail.com",
                            StudentName = "Anh Quý"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ninh Bình",
                            DOB = new DateTime(2003, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Luat001",
                            Email = "vanthao2306@gmail.com",
                            StudentName = "Vân Thảo"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hà Nội",
                            DOB = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tramy@gmail.com",
                            StudentName = "Trà My"
                        });
                });

            modelBuilder.Entity("CollegeApp.Data.Student", b =>
                {
                    b.HasOne("CollegeApp.Data.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_Student_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CollegeApp.Data.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
